spring.application.name=AviaSaler
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/aviasaler}
spring.datasource.username=${DB_USER:aviasaler}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

aviasales.api.base-url=https://api.travelpayouts.com
aviasales.api.token=${AVIASALES_TOKEN:}

# --- Telegram ---
telegram.bot-token=${TELEGRAM_BOT_TOKEN:}
telegram.chat-id=${TELEGRAM_CHAT_ID:}
